// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_log.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addEntry = `-- name: AddEntry :one
INSERT INTO access_log (user_id, stash_id, secret_name, action) VALUES (?, ?, ?, ?) RETURNING id
`

type AddEntryParams struct {
	UserID     string
	StashID    string
	SecretName string
	Action     string
}

func (q *Queries) AddEntry(ctx context.Context, arg AddEntryParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.addEntryStmt, addEntry,
		arg.UserID,
		arg.StashID,
		arg.SecretName,
		arg.Action,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAccessLog = `-- name: ListAccessLog :many
SELECT u.id, u.username, u.password_hash, u.locked, u.expired_at, u.created_at, s.id, s.name, s.description, s.maintainer_id, s.master_key_hash, s.encrypted_data, s.created_at, a.secret_name, a.action, a.created_at FROM access_log a INNER JOIN users u ON u.id = user_id INNER JOIN stashes s ON s.id = stash_id ORDER BY a.created_at DESC LIMIT ? OFFSET ?
`

type ListAccessLogParams struct {
	Limit  int64
	Offset int64
}

type ListAccessLogRow struct {
	User       User
	Stash      Stash
	SecretName string
	Action     string
	CreatedAt  time.Time
}

func (q *Queries) ListAccessLog(ctx context.Context, arg ListAccessLogParams) ([]*ListAccessLogRow, error) {
	rows, err := q.query(ctx, q.listAccessLogStmt, listAccessLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAccessLogRow
	for rows.Next() {
		var i ListAccessLogRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.PasswordHash,
			&i.User.Locked,
			&i.User.ExpiredAt,
			&i.User.CreatedAt,
			&i.Stash.ID,
			&i.Stash.Name,
			&i.Stash.Description,
			&i.Stash.MaintainerID,
			&i.Stash.MasterKeyHash,
			&i.Stash.EncryptedData,
			&i.Stash.CreatedAt,
			&i.SecretName,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
