// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addEntryStmt, err = db.PrepareContext(ctx, addEntry); err != nil {
		return nil, fmt.Errorf("error preparing query AddEntry: %w", err)
	}
	if q.addUserStmt, err = db.PrepareContext(ctx, addUser); err != nil {
		return nil, fmt.Errorf("error preparing query AddUser: %w", err)
	}
	if q.createStashStmt, err = db.PrepareContext(ctx, createStash); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStash: %w", err)
	}
	if q.deleteStashStmt, err = db.PrepareContext(ctx, deleteStash); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteStash: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getStashByIDStmt, err = db.PrepareContext(ctx, getStashByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetStashByID: %w", err)
	}
	if q.getUserByCredentialsStmt, err = db.PrepareContext(ctx, getUserByCredentials); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByCredentials: %w", err)
	}
	if q.getUserByIdStmt, err = db.PrepareContext(ctx, getUserById); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserById: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.listAccessLogStmt, err = db.PrepareContext(ctx, listAccessLog); err != nil {
		return nil, fmt.Errorf("error preparing query ListAccessLog: %w", err)
	}
	if q.listStashesStmt, err = db.PrepareContext(ctx, listStashes); err != nil {
		return nil, fmt.Errorf("error preparing query ListStashes: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.updateEncryptedDataStmt, err = db.PrepareContext(ctx, updateEncryptedData); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateEncryptedData: %w", err)
	}
	if q.updateStashStmt, err = db.PrepareContext(ctx, updateStash); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStash: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addEntryStmt != nil {
		if cerr := q.addEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addEntryStmt: %w", cerr)
		}
	}
	if q.addUserStmt != nil {
		if cerr := q.addUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addUserStmt: %w", cerr)
		}
	}
	if q.createStashStmt != nil {
		if cerr := q.createStashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStashStmt: %w", cerr)
		}
	}
	if q.deleteStashStmt != nil {
		if cerr := q.deleteStashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteStashStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getStashByIDStmt != nil {
		if cerr := q.getStashByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStashByIDStmt: %w", cerr)
		}
	}
	if q.getUserByCredentialsStmt != nil {
		if cerr := q.getUserByCredentialsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByCredentialsStmt: %w", cerr)
		}
	}
	if q.getUserByIdStmt != nil {
		if cerr := q.getUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIdStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.listAccessLogStmt != nil {
		if cerr := q.listAccessLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAccessLogStmt: %w", cerr)
		}
	}
	if q.listStashesStmt != nil {
		if cerr := q.listStashesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStashesStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.updateEncryptedDataStmt != nil {
		if cerr := q.updateEncryptedDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateEncryptedDataStmt: %w", cerr)
		}
	}
	if q.updateStashStmt != nil {
		if cerr := q.updateStashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStashStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                       DBTX
	tx                       *sql.Tx
	addEntryStmt             *sql.Stmt
	addUserStmt              *sql.Stmt
	createStashStmt          *sql.Stmt
	deleteStashStmt          *sql.Stmt
	deleteUserStmt           *sql.Stmt
	getStashByIDStmt         *sql.Stmt
	getUserByCredentialsStmt *sql.Stmt
	getUserByIdStmt          *sql.Stmt
	getUserByUsernameStmt    *sql.Stmt
	listAccessLogStmt        *sql.Stmt
	listStashesStmt          *sql.Stmt
	listUsersStmt            *sql.Stmt
	updateEncryptedDataStmt  *sql.Stmt
	updateStashStmt          *sql.Stmt
	updateUserStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                       tx,
		tx:                       tx,
		addEntryStmt:             q.addEntryStmt,
		addUserStmt:              q.addUserStmt,
		createStashStmt:          q.createStashStmt,
		deleteStashStmt:          q.deleteStashStmt,
		deleteUserStmt:           q.deleteUserStmt,
		getStashByIDStmt:         q.getStashByIDStmt,
		getUserByCredentialsStmt: q.getUserByCredentialsStmt,
		getUserByIdStmt:          q.getUserByIdStmt,
		getUserByUsernameStmt:    q.getUserByUsernameStmt,
		listAccessLogStmt:        q.listAccessLogStmt,
		listStashesStmt:          q.listStashesStmt,
		listUsersStmt:            q.listUsersStmt,
		updateEncryptedDataStmt:  q.updateEncryptedDataStmt,
		updateStashStmt:          q.updateStashStmt,
		updateUserStmt:           q.updateUserStmt,
	}
}
