// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type AccessLog struct {
	ID         uuid.UUID
	UserID     string
	StashID    string
	SecretName string
	Action     string
	CreatedAt  time.Time
}

type Stash struct {
	ID            uuid.UUID
	Name          string
	Description   interface{}
	MaintainerID  int64
	MasterKeyHash string
	EncryptedData *string
	CreatedAt     time.Time
}

type StashMember struct {
	UserID    string
	StashID   string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Locked       int64
	ExpiredAt    time.Time
	CreatedAt    time.Time
}
