// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type AccessLog struct {
	UserID     int64
	StashID    int64
	SecretName string
	Action     string
	CreatedAt  time.Time
}

type Stash struct {
	ID            int64
	Name          string
	MaintainerID  int64
	MasterKeyHash string
	MasterKeySalt string
	Content       []byte
	CreatedAt     time.Time
}

type StashMember struct {
	UserID    int64
	StashID   int64
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	PasswordSalt string
	Locked       int64
	ExpiredAt    time.Time
	CreatedAt    time.Time
}
