// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stashes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createStash = `-- name: CreateStash :one
INSERT INTO stashes (name, description, maintainer_id, master_key_hash, encrypted_data) VALUES (?, ?, ?, ?, ?) RETURNING id
`

type CreateStashParams struct {
	Name          string
	Description   interface{}
	MaintainerID  int64
	MasterKeyHash string
	EncryptedData *string
}

func (q *Queries) CreateStash(ctx context.Context, arg CreateStashParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.createStashStmt, createStash,
		arg.Name,
		arg.Description,
		arg.MaintainerID,
		arg.MasterKeyHash,
		arg.EncryptedData,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteStash = `-- name: DeleteStash :execrows
DELETE FROM stashes WHERE id = ?
`

func (q *Queries) DeleteStash(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.deleteStashStmt, deleteStash, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getStashByID = `-- name: GetStashByID :one
SELECT id, name, description, maintainer_id, master_key_hash, encrypted_data, created_at FROM stashes WHERE id = ?
`

func (q *Queries) GetStashByID(ctx context.Context, id uuid.UUID) (*Stash, error) {
	row := q.queryRow(ctx, q.getStashByIDStmt, getStashByID, id)
	var i Stash
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaintainerID,
		&i.MasterKeyHash,
		&i.EncryptedData,
		&i.CreatedAt,
	)
	return &i, err
}

const listStashes = `-- name: ListStashes :many
SELECT id, name, description, maintainer_id, master_key_hash, encrypted_data, created_at FROM stashes WHERE maintainer_id = ? LIMIT ? OFFSET ?
`

type ListStashesParams struct {
	MaintainerID int64
	Limit        int64
	Offset       int64
}

func (q *Queries) ListStashes(ctx context.Context, arg ListStashesParams) ([]*Stash, error) {
	rows, err := q.query(ctx, q.listStashesStmt, listStashes, arg.MaintainerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Stash
	for rows.Next() {
		var i Stash
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaintainerID,
			&i.MasterKeyHash,
			&i.EncryptedData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEncryptedData = `-- name: UpdateEncryptedData :execrows
UPDATE stashes SET encrypted_data = ? WHERE id = ?
`

type UpdateEncryptedDataParams struct {
	EncryptedData *string
	ID            uuid.UUID
}

func (q *Queries) UpdateEncryptedData(ctx context.Context, arg UpdateEncryptedDataParams) (int64, error) {
	result, err := q.exec(ctx, q.updateEncryptedDataStmt, updateEncryptedData, arg.EncryptedData, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateStash = `-- name: UpdateStash :execrows
UPDATE stashes SET name = ?, description = ?, master_key_hash = ?, encrypted_data = ? WHERE id = ?
`

type UpdateStashParams struct {
	Name          string
	Description   interface{}
	MasterKeyHash string
	EncryptedData *string
	ID            uuid.UUID
}

func (q *Queries) UpdateStash(ctx context.Context, arg UpdateStashParams) (int64, error) {
	result, err := q.exec(ctx, q.updateStashStmt, updateStash,
		arg.Name,
		arg.Description,
		arg.MasterKeyHash,
		arg.EncryptedData,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
