// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUser = `-- name: AddUser :one
INSERT INTO users(username, password_hash, password_salt)
VALUES (?, ?, ?) RETURNING id, username, password_hash, password_salt, locked, expired_at, created_at
`

type AddUserParams struct {
	Username     string
	PasswordHash string
	PasswordSalt string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (*User, error) {
	row := q.queryRow(ctx, q.addUserStmt, addUser, arg.Username, arg.PasswordHash, arg.PasswordSalt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.Locked,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByCredentials = `-- name: GetUserByCredentials :one
SELECT id, username, password_hash, password_salt, locked, expired_at, created_at FROM users WHERE username = ? AND password_hash = ?
`

type GetUserByCredentialsParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) GetUserByCredentials(ctx context.Context, arg GetUserByCredentialsParams) (*User, error) {
	row := q.queryRow(ctx, q.getUserByCredentialsStmt, getUserByCredentials, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.Locked,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password_hash, password_salt, locked, expired_at, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.queryRow(ctx, q.getUserByIdStmt, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.Locked,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, password_salt, locked, expired_at, created_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.Locked,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, password_salt, locked, expired_at, created_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.PasswordSalt,
			&i.Locked,
			&i.ExpiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users SET username = ?, password_hash = ?, password_salt = ?, locked = ?, expired_at = ? WHERE id = ?
`

type UpdateUserParams struct {
	Username     string
	PasswordHash string
	PasswordSalt string
	Locked       int64
	ExpiredAt    time.Time
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.exec(ctx, q.updateUserStmt, updateUser,
		arg.Username,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.Locked,
		arg.ExpiredAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
