name: stash-server

services:
  stash-air:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stash-server
    cap_add:
      - IPC_LOCK
    ports:
      - 7878:7878/tcp
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:18-trixie
    container_name: stash-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stash_db
    ports:
      - 5432:5432/tcp
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: {}
