name: stash-server-dev
services:
  postgres:
    image: postgres:18-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stash_db
    ports:
      - 5432:5432/tcp
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "$$POSTGRES_DB", "-U", "$$POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: {}
