FROM golang:1.26-alpine3.23

WORKDIR /app
RUN apk add --no-cache -X https://dl-cdn.alpinelinux.org/alpine/edge/community just 
RUN go install github.com/air-verse/air@latest
CMD [ "just", "run-air" ]
